port: 8080
ip: 127.0.0.1
host: www.baidu.com

base:
  redis:
    host: redis.dns.baidu.com
    port: 6379
    dataBase: 0
    timeout: 2000
  database:
    host: localhost
    port: 3306
    dbtype: mysql
    dbname: casbin
    username: root
    password: root
