port: 8080
ip: 127.0.0.1
host: www.baidu.com

base:
  redis:
    host: localhost
    port: 6379
    dataBase: 0
    timeout: 2000
    password: 123456
  database:
    host: localhost
    port: 33066
    dbtype: mysql
    dbname: casbin
    username: root
    password: root
    tablePrefix: t_
